name: Diagnostic

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ubuntu works"
  test-macos:
    runs-on: macos-latest
    steps:
      - run: echo "macos works"
